-- PRIMER CAMBIO --
ALTER TABLE RESERVAS MODIFY COLUMN cliente_id bigint NOT NULL;
ALTER TABLE RESERVAS MODIFY COLUMN prof_id bigint NOT NULL;
ALTER TABLE RESERVAS MODIFY COLUMN servicio_id bigint NOT NULL;
ALTER TABLE PROFESIONALES MODIFY COLUMN discriminator varchar(50) NOT NULL;