-- SEGUNDO CAMBIO --
ALTER TABLE USUARIOS MODIFY COLUMN nombre varchar(50) NOT NULL;
ALTER TABLE USUARIOS MODIFY COLUMN apellido varchar(50) NOT NULL;
ALTER TABLE USUARIOS MODIFY COLUMN telefono bigint NOT NULL;
ALTER TABLE DATOS_ACCESO MODIFY COLUMN estado varchar(50);
ALTER TABLE SERVICIOS MODIFY COLUMN estado varchar(50);
ALTER TABLE RESERVAS MODIFY COLUMN fecha DATETIME NOT NULL;
ALTER TABLE RESERVAS MODIFY COLUMN hora integer NOT NULL; 